import type { StoryEvent } from "./types";

export const STORY_EVENTS: Record<string, StoryEvent> = {
  // ── INTRO ──────────────────────────────────────────────────────────────────
  intro: {
    id: "intro",
    title: "The Crystal Crown of Lumina",
    lines: [
      "The village of Brightmoor has lived in peace for a thousand years,",
      "protected by the Crystal Crown of Lumina — an ancient artifact",
      "said to be the solidified light of the first dawn.",
      "",
      "Three nights ago, Malachar Darkstone, a wizard exiled for forbidden",
      "experiments, descended upon Brightmoor under cover of shadow.",
      "He shattered the Crown into five shards and fled into the caverns below.",
      "",
      "Without the Crown, Brightmoor's magical wards are failing.",
      "Darkness seeps in. Monsters stir in the streets.",
      "",
      "You are Ryn, apprentice to Elder Thornwood.",
      "You are the only one who can descend into the darkness,",
      "recover the Crown Shards, and restore the light.",
      "",
      "Take courage, young wizard. Brightmoor is counting on you.",
    ],
    speaker: "Elder Thornwood",
  },

  // ── FLOOR 1 — The Mossy Depths ─────────────────────────────────────────────
  floor_1_discover: {
    id: "floor_1_discover",
    title: "A Torn Journal",
    lines: [
      "You find a battered journal wedged between two mossy stones.",
      "",
      "\"...Day 4 in the caverns. The slimes are docile if you keep moving.",
      "The goblins are not. They remember your scent.",
      "",
      "I heard something ahead — a low, wet rumbling. The rocks shake.",
      "I fear what lives at the bottom of this level.",
      "",
      "If anyone reads this: the Crown Shard hums like a tuning fork.",
      "Follow the sound. You'll know when you're close.\"",
      "",
      "The rest of the pages are blank.",
    ],
    speaker: "A Lost Explorer",
  },
  floor_1_boss_intro: {
    id: "floor_1_boss_intro",
    title: "The Slime King",
    lines: [
      "The chamber opens into a vast underground garden.",
      "Bioluminescent mushrooms line the walls in violet and teal.",
      "",
      "In the center, a colossal slime pulses with grotesque life.",
      "Three red eyes blink open — slowly, lazily.",
      "",
      "It opens a mouth the size of a door.",
      "",
      "\"SQUISHHH... no one passes the Slime King...\"",
      "",
      "A crown shard glows through its translucent flesh.",
    ],
    speaker: "The Slime King",
  },
  floor_1_complete: {
    id: "floor_1_complete",
    title: "Shard Recovered!",
    lines: [
      "The Slime King collapses into a shimmering puddle.",
      "You reach into the goo (trying not to think about it)",
      "and pull free the first Crown Shard.",
      "",
      "It pulses warmly in your hand — a fragment of pure light.",
      "You can almost hear the village bells from here.",
      "",
      "The stairs downward beckon.",
      "Malachar won't stop at one shard.",
    ],
    speaker: undefined,
  },

  // ── FLOOR 2 — The Crystal Mines ────────────────────────────────────────────
  floor_2_discover: {
    id: "floor_2_discover",
    title: "A Trapped Miner",
    lines: [
      "You find a dusty old miner wedged into a crystal alcove,",
      "his lantern still flickering.",
      "",
      "\"Oh thank the Crown! A living soul!\"",
      "\"I was working the lower vein when Malachar passed through.\"",
      "\"He had this... black smoke around him. Everything he touched turned cold.\"",
      "",
      "\"He took something from the crystal at the center of this mine —\"",
      "\"I heard it crack. Like a heartbeat stopping.\"",
      "",
      "\"He spoke to it before he left. Said: 'Five pieces to unmake',\"",
      "\"'and the light of Lumina will never return.'\"",
      "",
      "\"Please... stop him. I'll find my own way out.\"",
    ],
    speaker: "Old Miner Gruff",
  },
  floor_2_boss_intro: {
    id: "floor_2_boss_intro",
    title: "The Crystal Guardian",
    lines: [
      "At the mine's deepest point, the walls explode with light.",
      "A towering being of living crystal rises from the floor,",
      "each facet reflecting a thousand broken images of you.",
      "",
      "\"I AM THE WARDEN OF THE DEEP SEAM.\"",
      "\"MALACHAR BOUND ME TO GUARD THIS PLACE.\"",
      "\"I... I do not wish to fight you...\"",
      "\"But I have no choice. Forgive me.\"",
      "",
      "Its crystal fist crashes toward you.",
    ],
    speaker: "Crystal Guardian",
  },

  // ── FLOOR 3 — The Sunken Catacombs ─────────────────────────────────────────
  floor_3_discover: {
    id: "floor_3_discover",
    title: "The Ghost of Sergeant Aldric",
    lines: [
      "A translucent figure materializes from the tomb wall.",
      "He wears the armor of Brightmoor's ancient guard.",
      "",
      "\"Wizard's apprentice, halt.\"",
      "\"I have waited two hundred years for someone like you to pass.\"",
      "",
      "\"Know this: Malachar is not simply evil. He was one of us once.\"",
      "\"A student of Lumina's College. Brilliant. Obsessed.\"",
      "",
      "\"He discovered that the Crown's light suppressed dark magic.\"",
      "\"Not to protect us — but to contain it from leaving this world.\"",
      "",
      "\"He believed the darkness deserved to be free.\"",
      "\"We believed he was wrong. We still do.\"",
      "",
      "\"His weakness: he cannot bear the light of a Crown Shard held aloft.\"",
      "\"When the moment comes, you will know what to do.\"",
    ],
    speaker: "Ghost of Sergeant Aldric",
  },
  floor_3_boss_intro: {
    id: "floor_3_boss_intro",
    title: "The Forgotten Knight",
    lines: [
      "Rusted armor assembles itself in the darkness,",
      "piece by piece, drawn together by ancient hatred.",
      "",
      "A hollow voice echoes from within the empty helm:",
      "",
      "\"I served this dungeon before the village above was a dream.\"",
      "\"Malachar promised me peace. He lied.\"",
      "\"He promised everyone peace. He always lies.\"",
      "",
      "\"Defeat me and earn the right to face him.\"",
      "\"I will finally rest.\"",
    ],
    speaker: "The Forgotten Knight",
  },

  // ── FLOOR 4 — The Dark Academy ─────────────────────────────────────────────
  floor_4_discover: {
    id: "floor_4_discover",
    title: "Malachar's Private Journal",
    lines: [
      "You discover a lectern holding an open journal,",
      "its pages still warm as if recently written.",
      "",
      "\"The villagers call me a monster.\"",
      "\"They forget I spent thirty years healing their sick,\"",
      "\"lighting their harvest festivals, tutoring their children.\"",
      "",
      "\"Then I found the truth beneath the Crown.\"",
      "\"Lumina didn't create the light. She imprisoned the dark.\"",
      "\"Stripped it of freedom. Forced 'harmony' at the cost of truth.\"",
      "",
      "\"They cast me out when I told them.\"",
      "\"So be it. If they love their comfortable lie,\"",
      "\"they can live without the thing that powers it.\"",
      "",
      "\"Let them face the real world. Like I had to.\"",
    ],
    speaker: "Malachar's Journal",
  },
  floor_4_boss_intro: {
    id: "floor_4_boss_intro",
    title: "The Dark Apprentice",
    lines: [
      "A young man in black robes blocks your path.",
      "He can't be older than you.",
      "",
      "\"Ryn. I know your name. Master Malachar told me about you.\"",
      "\"He said you'd be exactly like the others. Blind. Obedient.\"",
      "",
      "\"I used to be like you. Then he showed me the truth.\"",
      "\"The dark isn't evil. The Crown just made you afraid of it.\"",
      "",
      "\"I can't let you past. I'm sorry.\"",
      "",
      "He raises his staff — and the shadows gather.",
    ],
    speaker: "Dorin, Dark Apprentice",
  },
  floor_4_boss_defeat: {
    id: "floor_4_boss_defeat",
    title: "Dorin's Last Words",
    lines: [
      "Dorin collapses to one knee, his black robes flickering back to grey.",
      "",
      "\"You're... stronger than I expected.\"",
      "",
      "\"He said the Crown's light was oppression.\"",
      "\"But when you held it just now... it didn't feel like a cage.\"",
      "\"It felt like morning.\"",
      "",
      "\"Go. Stop him. I think... I think I made a mistake.\"",
      "",
      "He presses the fourth shard into your hand and slumps against the wall.",
      "",
      "\"Tell Brightmoor... tell them I'm sorry.\"",
    ],
    speaker: "Dorin",
  },

  // ── FLOOR 5 — Malachar's Sanctum ───────────────────────────────────────────
  floor_5_discover: {
    id: "floor_5_discover",
    title: "The Sanctum Speaks",
    lines: [
      "The walls of this chamber are alive with dark energy.",
      "Shadows writhe across every surface.",
      "The air tastes of lightning and old sorrow.",
      "",
      "Malachar's voice echoes from everywhere and nowhere.",
      "",
      "\"You've come further than I expected, young Ryn.\"",
      "\"But ask yourself: what awaits you if you succeed?\"",
      "",
      "\"You'll restore the Crown. The village will cheer.\"",
      "\"Then another generation will grow up believing the lie.\"",
      "\"Never questioning. Never knowing.\"",
      "",
      "\"Is that truly what you're fighting for?\"",
      "",
      "You grip your staff tighter.",
      "You know exactly what you're fighting for.",
    ],
    speaker: "Malachar Darkstone",
  },
  floor_5_boss_intro: {
    id: "floor_5_boss_intro",
    title: "Malachar Darkstone",
    lines: [
      "He is older than you imagined. Tired-looking, even.",
      "Five Crown Shards orbit him like dark moons,",
      "their light twisted and suppressed.",
      "",
      "\"You have your four. I have my one. Fitting.\"",
      "",
      "\"I won't pretend to enjoy this, Ryn.\"",
      "\"You remind me of myself, once upon a time.\"",
      "",
      "\"But I've come too far to stop now.\"",
      "\"The darkness will be free tonight.\"",
      "",
      "\"Forgive an old man his obsession.\"",
      "",
      "Shadows detonate outward. The final battle begins.",
    ],
    speaker: "Malachar Darkstone",
  },
  victory: {
    id: "victory",
    title: "The Crown Restored",
    lines: [
      "Malachar falls.",
      "The fifth shard cracks free from his orbit and lands in your hand.",
      "",
      "All five pieces sing together — a sound like a sunrise made audible.",
      "They fuse. Glow. The Crystal Crown of Lumina is whole once more.",
      "",
      "Malachar looks up from the floor, his face slack with exhaustion.",
      "",
      "\"Well. It seems the light endures.\"",
      "",
      "\"Perhaps... there was always room for both.\"",
      "\"Perhaps I was simply too angry to see it.\"",
      "",
      "He closes his eyes. The darkness retreats.",
      "",
      "Above, in Brightmoor, every lamp flares back to life.",
      "The wards snap back into place. The monsters flee.",
      "",
      "You carry the Crown upward, toward the morning.",
      "",
      "    ✦  Brightmoor is saved.  ✦",
      "    ✦  The light endures.   ✦",
    ],
    speaker: undefined,
  },
};
